# Generated by Django 3.1 on 2020-09-30 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='DemoAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_answer', models.CharField(max_length=255, unique=True, verbose_name='DemoAnswers')),
            ],
        ),
        migrations.CreateModel(
            name='DemoQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_question', models.CharField(max_length=255, verbose_name='DemoQuestions')),
                ('demo_answer', models.ForeignKey(db_column='DemoAnswers', on_delete=django.db.models.deletion.CASCADE, to='backend_main.demoanswers', to_field='demo_answer')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_main.answers')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_main.answers')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_main.questions')),
            ],
        ),
        migrations.CreateModel(
            name='DemoTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_main.demoanswers')),
                ('demo_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_main.demoquestions')),
            ],
        ),
    ]
