# Generated by Django 3.1.2 on 2020-10-03 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255, unique=True, verbose_name='Answer')),
            ],
        ),
        migrations.CreateModel(
            name='DemoAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_answer', models.CharField(max_length=255, unique=True, verbose_name='DemoAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='DemoUserTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('demoUserEmail', models.EmailField(blank=True, max_length=255, verbose_name='Demo User Email')),
                ('dateOfStart', models.DateField(auto_now_add=True, verbose_name='Day of Start Demo Test')),
                ('timeStart', models.TimeField(auto_now_add=True, verbose_name='Start Time of Demo Test')),
                ('timeEnd', models.TimeField(auto_now=True, verbose_name='End Time of Demo Test')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer_id', models.ForeignKey(db_column='Answer', on_delete=django.db.models.deletion.CASCADE, to='backend_main.answer', to_field='answer')),
            ],
        ),
        migrations.CreateModel(
            name='DemoQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo_question', models.CharField(max_length=255, verbose_name='DemoQuestions')),
                ('demo_answer', models.ForeignKey(db_column='DemoAnswer', on_delete=django.db.models.deletion.CASCADE, to='backend_main.demoanswer', to_field='demo_answer')),
            ],
        ),
    ]
