# Generated by Django 3.1.2 on 2020-10-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demousertest',
            name='demoGrade',
            field=models.CharField(max_length=5, null=True, verbose_name='Demo Grade'),
        ),
    ]
