# Generated by Django 3.1 on 2020-09-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='question_id',
        ),
        migrations.RemoveField(
            model_name='demoanswers',
            name='demo_question_id',
        ),
    ]
