# Generated by Django 3.1.2 on 2020-10-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_auto_20201003_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demousertest',
            name='dateOfStart',
            field=models.DateField(auto_now_add=True, verbose_name='Day of Start Demo Test'),
        ),
    ]
